# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c149eb61ecd01e4effc063ad59ba0cee2c20ffc8966e4471cf475502509dd055042a14ca82f5c84fa443318cc3d3ed7620c9e5f1f41a6c3b335d35c0b31e2e7

test:
  secret_key_base: ce856d703c89ca1730368d86ca61bf65f40d894bcfe6fffa45b49e2cec41ae5dbe2311f47bf8a169ae6bb1f7b833e187e93ca9bc1a5196450bedcbb41a90afae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
